### ISSUE TITLE
Rotor Http

### ISSUE THREAD

**Issue by KodrAus** [KodrAus/elasticsearch-rs#31]
Long term, it looks like the new `rotor_http` might be a good base for building the HTTP off.

https://github.com/tailhook/rotor-http/blob/master/src/client/request.rs

## Tasks

- [x] Http GET connection to `/_search`
- [x] Http POST connection to `/_search` with body
- [x] Loop in separate thread that takes commands via `Notifier`
- [x] Persistent connection to `/_search` with various bodies

**Comment by KodrAus** [comment]
See: https://github.com/tailhook/rotor-http/blob/master/examples/client.rs

Current rotor-http client API looks like this:

```
extern crate rotor;
extern crate rotor_http;
extern crate time;

use std::io::stdout;
use std::io::Write;
use std::net::ToSocketAddrs;

use rotor::{Scope};
use rotor_http::client::{connect_tcp, Request, Head, Client, RecvMode};
use rotor_http::client::{Context as HttpCtx};
use rotor_http::method::Method::Get;
use rotor_http::version::HttpVersion::Http11;
use rotor_http::Deadline;

struct Context;

impl HttpCtx for Context {}

struct Req(String);

impl Client for Req {
    type Context = Context;
    fn prepare_request(self, req: &mut Request) -> Option<Self> {
        req.start(Get, &self.0, Http11);
        req.done_headers().unwrap();
        req.done();
        Some(self)
    }
    fn headers_received(self, head: Head, _request: &mut Request,
        _scope: &mut Scope<Self::Context>)
        -> Option<(Self, RecvMode, Deadline)>
    {
        println!("----- Headers -----");
        println!("Status: {} {}", head.code, head.reason);
        for header in head.headers {
            println!("{}: {}", header.name,
                String::from_utf8_lossy(header.value));
        }
        Some((self,  RecvMode::Buffered(16386), Deadline::now() +
            time::Duration::seconds(1000)))
    }
    fn response_received(self, data: &[u8], _request: &mut Request,
        scope: &mut Scope<Self::Context>)
    {
        println!("----- Response -----");
        stdout().write_all(data).unwrap();
        if data.last() != Some(&b'\n') {
            println!("");
        }
        scope.shutdown_loop();
    }
    fn response_chunk(self, _chunk: &[u8], _request: &mut Request,
        _scope: &mut Scope<Self::Context>)
        -> Option<Self>
    {
        unreachable!();
    }
    fn response_end(self, _request: &mut Request,
        _scope: &mut Scope<Self::Context>)
    {
        unreachable!();
    }
    fn timeout(self, _request: &mut Request, _scope: &mut Scope<Self::Context>)
        -> Option<(Self, Deadline)>
    {
        unreachable!();
    }
    fn wakeup(self, _request: &mut Request, _scope: &mut Scope<Self::Context>)
        -> Option<Self>
    {
        unimplemented!();
    }
}


fn main() {
    let creator = rotor::Loop::new(&rotor::Config::new()).unwrap();
    let mut loop_inst = creator.instantiate(Context);
    loop_inst.add_machine_with(|scope| {
        connect_tcp(scope,
            &("google.com", 80).to_socket_addrs()
                .unwrap().collect::<Vec<_>>()[0],
            Req(format!("/")))
    }).unwrap();
    loop_inst.run().unwrap();
}
```

**Comment by KodrAus** [comment]
Add mockup for Rotor http (with `mpsc` or something) to [benches](https://github.com/KodrAus/elasticsearch-rs/blob/master/dev/es_benches/benches/mod.rs) for testing

**Comment by KodrAus** [comment]
A work in progress rotor client is coming along. It's a total mess right now, I'm just trying to get things to compile and run. I'd like to offer a promise-based design that just uses channels to block when a response is required. Rotor makes it easy to offer any abstraction over the top, so if the more imperative design isn't great I can switch it up.

See: https://github.com/KodrAus/elasticsearch-rs/blob/master/dev/es_benches_rust/src/main.rs for progress.

**Comment by KodrAus** [comment]
Still need to work out how to interact with a running rotor loop. See https://github.com/tailhook/rotor/issues/6

**Comment by KodrAus** [comment]
Would like to start working on this fairly soon

**Comment by KodrAus** [comment]
There's going to be some subtlety in the design of the rotor client, I'll need to set up a connection pool and use persistent connections where possible to Elasticsearch. Will need some way to choose an idle connection to use, and what to do if there are none available (ad-hoc request, or wait? Probably wait). Will also need to design the pool to be useful either manually for connections, or when managed by a cluster sniffer.

The poll will be recommended to run on its own thread, where communication is via channels.

**Comment by KodrAus** [comment]
Some thoughts on `elastic_rotor` design:

There's an issue where the only way we can get a queue that a machine can listen on is to put it on the Context.

The issue with this is that the Context is completely disjointed from the machine, and that means we can have queues with no listening machines. This will be difficult to debug.

My current line of thinking is as follows:

- Create a struct to wrap the `MsQueue`, that will also maintain a list of listeners.
- It should not be possible to access the queue without registering first.
- If the reference count drops to 0, also drop the queue.
- If the queue contains items when it's dropped, panic (if we don't allow queues with no listeners).

This should be fine to enforce semantically since only ElasticConnections will be using the ElasticContext.
The implementation should be easily composable if anyone wants to use multiple loops for the one machine.

So, the queue lifecycle is as follows:

1 User specifies queue 'address' when creating machine. This could be the host (default), or something they come up with
1 Machines that are created can either be given a queue address, or asked to get/add the default one for their host
1 When machines are closed, they decrement their counter for their queue
1 When the listener count falls to 0, the queue is dropped

```
struct MachineQueue {
	listeners: usize,
	queue: MsQueue
}
impl MachineQueue {
	add_listener(&mut self) {
		self.listeners += 1;
	}

	remove_listener(&mut self) {
		self.listeners -= 1;
	}

	push(&self, req: Request) -> Result<()> {
		if listeners.len() > 0 {
			self.queue.push(req);
			Ok(())
		}
		else {
			Err("no listeners registered")
		}
	}

	try_pop(&self) -> Option<Request> {
		self.queue.try_pop()
	}
}
```

**Comment by KodrAus** [comment]
We need to be able to provide the following functionality in the rotor loop:

- Register and deregister with a queue
- Determine the suitability of a queue for a particular request
- Resize / register more machines?

The expected use-case for `elastic_rotor` is heavy-duty io, so handlers should be getting spanked. This means having a good set of workers known upfront can make sense. Using a channel to get requests into the loop is pretty much the only way I can think of so far

**Comment by KodrAus** [comment]
The `MachineQueue` should be an enum, with the following states:

```
enum MachineQueue {
    NoListeners(MsQueue),
    Ready(MsQueue, BTreeMap<Notifier>)
}
```

Where we check the state before allowing messages to be added or removed. When running the loop initially, all queues in state `NoListeners` should be removed.

**Comment by KodrAus** [comment]
After spending some more time going through `rotor`, it looks like a better approach would be to have some root `ElasticRouter` machine, that maintains a list of child machines. Each child machine could then have a queue that it reads off.

The routing machine can push a request onto a child's queue for it to handle. That way, we can add new machines to an active loop.

**Comment by KodrAus** [comment]
![20160705_110514](https://cloud.githubusercontent.com/assets/6721458/16571495/9f41d376-42a0-11e6-9f0e-d62abe69814f.jpg)

Difficult to follow, but the idea is to have a slab of persistent conn machines known when the loop is built, that are connected based on sniffed cluster info. The state of the cluster lives in Context, and is periodically updated. Machines pinch an addr from the cluster to connect to (need to figure out how to work this with Persistent FSMs from rotor-http). Requests are then forwarded to one of the machines to handle.

The idea is that it isn't necessary to maintain a conn to _all_ nodes in the clustee at all times. Just a set amount for failover.

Ad-hoc requests can follow the hyper approach and encapsulate their own loop.

**Comment by KodrAus** [comment]
Looking at a variation on the above, where we have some 'global' queue(s) with references given to an FSM in exchange for a Notifier, which is added to a list of listeners.

There is a single FSM created per address. If addresses come and go, so do the FSMs. We can use Spawn to handle this.

Not sure about sniffing yet, maybe either a single sniffer machine that chooses a random address to sniff from, a set address, or allow any FSM to sniff?

**Comment by KodrAus** [comment]
Use [Futures](http://alexcrichton.com/futures-rs/futures/fn.promise.html) for returning responses asynchronously.

Also need to work around waking up every machine every time a new machine arrives... If we do a round robin then utilisation could be potwntially low

**Comment by KodrAus** [comment]
I'm going to close this now. There is a (not very good) `rotor` implementation, but I'd like to look into a `tokio` client. I like `rotor`, and think for app-level io it's a great fit, but isn't really composable, so doesn't make sense for lower-level clients.
